// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Posts []*Post `json:"posts"`
}

type EditedPost struct {
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	CreatedAt *string `json:"created_At"`
	UpdatedAt *string `json:"updated_At"`
}

type Post struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	CreatedAt string  `json:"created_At"`
	UpdatedAt string  `json:"updated_At"`
	Author    *Author `json:"author"`
}
